### ISSUE TITLE
可以开启简易模式和复制为图片的功能吗？

### ISSUE THREAD

**Issue by 362700** [zt8989/siyuan-drawio-plugin#6]
目前drawio插件缺乏这两个功能，还是非常重要的，希望可以加上，感谢！
插件非常nice，谢谢您开发出这么好用的工具！！！
<img width="920" alt="简易模式" src="https://github.com/user-attachments/assets/bf80c895-5738-474d-b44a-17afc2f322c2">
<img width="667" alt="复制为图像" src="https://github.com/user-attachments/assets/ba86c426-1023-4b30-9b3c-8be6a36c389d">

**Comment by zt8989** [comment]
依赖的是开源版的 drawio，目前不支持简易模式
